### ISSUE TITLE
用 CleanMyMac 清一下电脑之后会丢失配置

### ISSUE THREAD

**Issue by rccoder** [chenxtdo/UPImageMacApp#10]
RT.

是否可以考虑换存储路径或者其他方式存储，躲过 CleanMyMac 的清理

**Comment by chenxtdo** [comment]
好的，感谢反馈 发自网易邮箱大师 在2017年03月05日 20:38，Shangbin Yang 写道： RT. 是否可以考虑换存储路径或者其他方式存储，躲过 CleanMyMac 的清理 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by chenxtdo** [comment]
改了下路径，本地测试OK，MAS 已做提交。

**Comment by rccoder** [comment]
@chenxtdo 😆
