### ISSUE TITLE
验证失败

### ISSUE THREAD

**Issue by tracerZzz** [chenxtdo/UPImageMacApp#18]
验证失败，请仔细填写信息，之前用的都没问题，今天发现一只验证失败，请帮忙解决一下

**Comment by tracerZzz** [comment]
使用的是最新的版本 1.55

**Comment by MyHerux** [comment]
验证失败加一

**Comment by chenxtdo** [comment]
我看一下

**Comment by chenxtdo** [comment]
已经解决 下载 1.56 
https://github.com/chenxtdo/UPImageMacApp/releases/download/1.56/PicU.1.0.dmg

**Comment by chenxtdo** [comment]
@tracerZzz  @MyHerux

**Comment by tracerZzz** [comment]
可以啦 @chenxtdo 多谢啦
