### ISSUE TITLE
更新系统后无法打开、

### ISSUE THREAD

**Issue by 5am3** [chenxtdo/UPImageMacApp#21]
更新系统后无法打开、RT

Mojave 10.14.5 (18F203)

**Comment by beiliao-mobile** [comment]
catalina 打不开了

**Comment by chenxtdo** [comment]
需要抽个时间，使用新版本 swift 重写一遍

**Comment by MyHerux** [comment]
作者大大快更新呀，这是我Mac上使用频率最高的一批软件之一

**Comment by chenxtdo** [comment]
@MyHerux  @beiliao-mobile  @5am3  
现在自定义七牛可用，sm.ms 服务后面再更新
https://github.com/chenxtdo/UPImageMacApp/releases/tag/1.60
