### ISSUE TITLE
上传图片以后，返回的一直是默认图片地址链接

### ISSUE THREAD

**Issue by chenxiny** [chenxtdo/UPImageMacApp#6]
我自己的七牛已经提示验证成功了，但是不知道为什么上传图片一直下面这个域名。。。。 估计是默认配置吧。 我把自己的设置无论设置成http还是https都七牛域名 都解决不了问题。谢谢
http://7xqmjb.com1.z0.glb.clouddn.com/201701018199699.gif

**Comment by chenxtdo** [comment]
@chenxiny  最新的app store 版本是有存在这个bug。源码里已经修复。修复版本已经提交（还在审核中）。请耐心等待更新，或使用源码安装

**Comment by chenxtdo** [comment]
@chenxiny  已经更新，app store

**Comment by chenxiny** [comment]
感谢回复！
